import {
  FirearmVisualAssetManifest,
  FirearmVisualLayerAsset,
  FirearmVisualSlot,
} from "./types";

/**
 * Statically-typed manifest mapping each firearm type to its base silhouette
 * and supported accessory layers. Static `require()` calls mean a missing or
 * misnamed asset fails at bundle time, not at runtime — never construct
 * `require()` paths dynamically.
 *
 * Assets are SVG wireframes sharing one 1024x1024 viewBox per family; they are
 * generated by scripts/generate-firearm-assets.mjs and verified by
 * scripts/verify-firearm-assets.mjs. Edit the generator, not the files.
 */
const layer = (
  source: number,
  visualSlot: FirearmVisualSlot,
  zIndex: number
): FirearmVisualLayerAsset => ({ source, visualSlot, zIndex });

const Z = {
  muzzle: 10,
  support: 15,
  sideRail: 20,
  underbarrel: 20,
  opticAuxiliary: 35,
  primaryOptic: 40,
} as const;

export const FIREARM_VISUAL_ASSETS = {
  pistol: {
    base: require("../../../assets/images/firearms/pistol/base.svg"),
    layers: {
      red_dot: layer(
        require("../../../assets/images/firearms/pistol/layers/red-dot.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      flashlight: layer(
        require("../../../assets/images/firearms/pistol/layers/flashlight.svg"),
        "side_rail",
        Z.sideRail
      ),
      laser: layer(
        require("../../../assets/images/firearms/pistol/layers/laser.svg"),
        "side_rail",
        Z.sideRail
      ),
      suppressor: layer(
        require("../../../assets/images/firearms/pistol/layers/suppressor.svg"),
        "muzzle",
        Z.muzzle
      ),
    },
  },
  revolver: {
    base: require("../../../assets/images/firearms/revolver/base.svg"),
    layers: {},
  },
  pcc: {
    base: require("../../../assets/images/firearms/pcc/base.svg"),
    layers: {
      red_dot: layer(
        require("../../../assets/images/firearms/pcc/layers/red-dot.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      magnifier: layer(
        require("../../../assets/images/firearms/pcc/layers/magnifier.svg"),
        "optic_auxiliary",
        Z.opticAuxiliary
      ),
      scope: layer(
        require("../../../assets/images/firearms/pcc/layers/scope.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      flashlight: layer(
        require("../../../assets/images/firearms/pcc/layers/flashlight.svg"),
        "side_rail",
        Z.sideRail
      ),
      laser: layer(
        require("../../../assets/images/firearms/pcc/layers/laser.svg"),
        "side_rail",
        Z.sideRail
      ),
      suppressor: layer(
        require("../../../assets/images/firearms/pcc/layers/suppressor.svg"),
        "muzzle",
        Z.muzzle
      ),
      grip: layer(
        require("../../../assets/images/firearms/pcc/layers/grip.svg"),
        "underbarrel",
        Z.underbarrel
      ),
    },
  },
  rifle: {
    base: require("../../../assets/images/firearms/rifle/base.svg"),
    layers: {
      red_dot: layer(
        require("../../../assets/images/firearms/rifle/layers/red-dot.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      magnifier: layer(
        require("../../../assets/images/firearms/rifle/layers/magnifier.svg"),
        "optic_auxiliary",
        Z.opticAuxiliary
      ),
      scope: layer(
        require("../../../assets/images/firearms/rifle/layers/scope.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      flashlight: layer(
        require("../../../assets/images/firearms/rifle/layers/flashlight.svg"),
        "side_rail",
        Z.sideRail
      ),
      laser: layer(
        require("../../../assets/images/firearms/rifle/layers/laser.svg"),
        "side_rail",
        Z.sideRail
      ),
      suppressor: layer(
        require("../../../assets/images/firearms/rifle/layers/suppressor.svg"),
        "muzzle",
        Z.muzzle
      ),
      bipod: layer(
        require("../../../assets/images/firearms/rifle/layers/bipod.svg"),
        "support",
        Z.support
      ),
      grip: layer(
        require("../../../assets/images/firearms/rifle/layers/grip.svg"),
        "underbarrel",
        Z.underbarrel
      ),
    },
  },
  bolt_action_rifle: {
    base: require("../../../assets/images/firearms/bolt-action-rifle/base.svg"),
    layers: {
      scope: layer(
        require("../../../assets/images/firearms/bolt-action-rifle/layers/scope.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      suppressor: layer(
        require("../../../assets/images/firearms/bolt-action-rifle/layers/suppressor.svg"),
        "muzzle",
        Z.muzzle
      ),
      bipod: layer(
        require("../../../assets/images/firearms/bolt-action-rifle/layers/bipod.svg"),
        "support",
        Z.support
      ),
    },
  },
  shotgun: {
    base: require("../../../assets/images/firearms/shotgun/base.svg"),
    layers: {
      red_dot: layer(
        require("../../../assets/images/firearms/shotgun/layers/red-dot.svg"),
        "primary_optic",
        Z.primaryOptic
      ),
      flashlight: layer(
        require("../../../assets/images/firearms/shotgun/layers/flashlight.svg"),
        "side_rail",
        Z.sideRail
      ),
    },
  },
  other: {
    base: require("../../../assets/images/firearms/other/base.svg"),
    layers: {},
  },
} satisfies FirearmVisualAssetManifest;
